const API='https://api.alquran.cloud/v1', TOTAL=6236, DAY=86400000;
const defaultState={mastered:{},reviews:{},sessions:0,activity:{},plan:{newDaily:5,reviewDaily:20},tests:{correct:0,total:0}};
let state;try{state=Object.assign({},defaultState,JSON.parse(localStorage.getItem('hifzState')||'{}'));state.plan=Object.assign({},defaultState.plan,state.plan);state.tests=Object.assign({},defaultState.tests,state.tests);state.activity=state.activity||{};}catch(e){state=structuredClone(defaultState)}
const $=id=>document.getElementById(id), todayKey=()=>new Date().toISOString().slice(0,10), save=()=>{localStorage.setItem('hifzState',JSON.stringify(state));renderStats();renderToday()};
let surahs=[],current=[];
async function init(){try{surahs=(await (await fetch(API+'/surah')).json()).data;fill('surah');fill('testSurah');}catch(e){$('ayahs').innerHTML='<p>تعذر الاتصال. يلزم الإنترنت أول مرة لتحميل السور، وبعدها تحفظ السور على الجهاز.</p>'}$('dailyTarget').value=state.plan.newDaily;$('dailyReview').value=state.plan.reviewDaily;renderStats();renderReview();renderToday()}
function fill(id){$(id).innerHTML=surahs.map(x=>`<option value="${x.number}">${x.number}. ${x.name} — ${x.numberOfAyahs} آية</option>`).join('')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='review')renderReview();if(b.dataset.tab==='today')renderToday();if(b.dataset.tab==='weak')renderWeak()});
async function getSurah(n){const key='surah_'+n,d=localStorage.getItem(key);if(d)return JSON.parse(d);const r=await fetch(`${API}/surah/${n}/quran-uthmani`);if(!r.ok)throw Error();const j=await r.json();localStorage.setItem(key,JSON.stringify(j.data.ayahs));return j.data.ayahs}
$('load').onclick=async()=>{try{const n=+$('surah').value,a=+$('fromAyah').value,b=+$('toAyah').value,all=await getSurah(n);current=all.filter(x=>x.numberInSurah>=a&&x.numberInSurah<=b);$('ayahs').innerHTML=current.map(x=>`<div class="ayah">${x.text} <small>﴿${x.numberInSurah}﴾</small></div>`).join('')||'<p>تحقق من نطاق الآيات.</p>'}catch(e){alert('تعذر تحميل السورة. تحقق من الإنترنت.') }};
$('toggle').onclick=()=>document.querySelectorAll('#ayahs .ayah').forEach(x=>x.classList.toggle('hide'));
$('mark').onclick=()=>{if(!current.length)return alert('حمّل الآيات أولاً.');const n=+$('surah').value,now=Date.now();current.forEach(x=>{const k=`${n}:${x.numberInSurah}`;state.mastered[k]=true;state.reviews[k]=state.reviews[k]||{due:now+DAY,level:1}});state.sessions++;state.activity[todayKey()]=(state.activity[todayKey()]||0)+current.length;save();alert('تم تسجيل الحفظ وإضافته إلى دورة المراجعة.')};
function renderReview(){const box=$('reviewList'),now=Date.now();const due=Object.entries(state.reviews).filter(([,v])=>v.due<=now).sort((a,b)=>a[1].due-b[1].due);if(!due.length){box.innerHTML='<p>لا توجد مراجعات مستحقة الآن.</p>';return}box.innerHTML=due.slice(0,state.plan.reviewDaily).map(([k,v])=>`<div class="card" style="margin:8px 0"><b>موضع ${k.replace(':','، الآية ')}</b> <span class="pill">المستوى ${v.level}</span><div class="row"><button onclick="rate('${k}',0)">ضعيف</button><button onclick="rate('${k}',1)">جيد</button><button class="primary" onclick="rate('${k}',2)">متقن</button></div></div>`).join('')}
window.rate=(k,r)=>{let v=state.reviews[k]||{level:1};v.level=Math.max(1,Math.min(7,v.level+(r===2?1:r===0?-1:0)));const intervals=r===0?[0,1,1,2,3,4,7]:[1,2,4,7,14,30,60];v.due=Date.now()+intervals[v.level-1]*DAY;state.reviews[k]=v;save();renderReview()};
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
$('startTest').onclick=async()=>{try{let n=+$('testSurah').value,type=$('testType').value,all;if(type==='saved'){const keys=Object.keys(state.mastered);if(!keys.length)return alert('سجّل بعض الآيات كمحفوظة أولاً.');const k=keys[Math.floor(Math.random()*keys.length)].split(':');n=+k[0];all=await getSurah(n);let idx=+k[1]-1;const a=all[idx];testArea.innerHTML=`<div class="testbox">اختبار شامل للمحفوظ<br><b>${a.text}</b><br><small>سورة ${surahs.find(x=>x.number===n)?.name||n} • الآية ${a.numberInSurah}</small><br>سمّع من هذا الموضع ثم قيّم نفسك.</div><div class="row"><button onclick="selfTest(0,'${n}:${a.numberInSurah}')">ضعيف</button><button onclick="selfTest(1,'${n}:${a.numberInSurah}')">جيد</button><button class="primary" onclick="selfTest(2,'${n}:${a.numberInSurah}')">متقن</button></div>`;return}all=await getSurah(n);if(all.length<2)return;let i=Math.floor(Math.random()*Math.max(1,all.length-2));if(type==='previous')i=Math.max(1,i);const a=all[i],next=all[i+1],prev=all[i-1];if(type==='random'){testArea.innerHTML=`<div class="testbox">ابدأ التسميع من:<br><b>${a.text}</b><br>﴿${a.numberInSurah}﴾</div><button class="primary" onclick="showSequence(${n},${i})">إظهار الآيات التالية</button>`;return}if(type==='complete'){let w=a.text.split(' '),cut=Math.max(1,Math.floor(w.length*.55));testArea.innerHTML=`<div class="testbox">${w.slice(0,cut).join(' ')} …</div><button class="primary" onclick="reveal(this,${JSON.stringify(a.text)})">إظهار الإجابة</button>`;return}if(type==='order'){let seq=all.slice(i,i+3);testArea.innerHTML=`<div class="testbox">رتّب هذه الآيات ذهنيًا ثم تحقق:</div>${shuffle(seq).map(x=>`<button class="choice">${x.text}</button>`).join('')}<button class="primary" onclick="showOrder(${n},${i})">إظهار الترتيب الصحيح</button>`;return}const answer=type==='next'?next:prev,prompt=a;let opts=[answer];while(opts.length<Math.min(4,all.length)){let x=all[Math.floor(Math.random()*all.length)];if(x&&!opts.some(o=>o.number===x.number))opts.push(x)}opts=shuffle(opts);testArea.innerHTML=`<div class="testbox">${prompt.text}<br><small>${type==='next'?'ما الآية التالية؟':'ما الآية السابقة؟'}</small></div>`+opts.map(o=>`<button class="choice" onclick="checkChoice(this,${o.number===answer.number})">${o.text}</button>`).join('')}catch(e){alert('تعذر بدء الاختبار. حمّل السورة مع الإنترنت أولاً.')}};
window.reveal=(b,t)=>{b.previousElementSibling.textContent=t};window.showSequence=async(n,i)=>{const all=await getSurah(n);testArea.innerHTML+=all.slice(i+1,i+4).map(x=>`<div class="ayah">${x.text} ﴿${x.numberInSurah}﴾</div>`).join('')};window.showOrder=async(n,i)=>{const all=await getSurah(n);testArea.innerHTML=all.slice(i,i+3).map(x=>`<div class="ayah">${x.text} ﴿${x.numberInSurah}﴾</div>`).join('')};window.checkChoice=(b,ok)=>{document.querySelectorAll('.choice').forEach(x=>x.disabled=true);b.classList.add(ok?'ok':'bad');state.tests.total++;if(ok)state.tests.correct++;save();$('testScore').textContent=`نتيجة الاختبارات: ${state.tests.correct} صحيحة من ${state.tests.total}`;if(ok)setTimeout(()=>$('startTest').click(),800)};
$('savePlan').onclick=()=>{state.plan.newDaily=Math.max(1,+$('dailyTarget').value||5);state.plan.reviewDaily=Math.max(5,+$('dailyReview').value||20);save();alert('تم حفظ خطة الحفظ والمراجعة.')};
function streakCount(){let n=0,d=new Date();for(;;){const k=d.toISOString().slice(0,10);if(state.activity[k]){n++;d.setDate(d.getDate()-1)}else break}return n}
function renderToday(){const m=Object.keys(state.mastered).length,left=TOTAL-m,days=Math.ceil(left/state.plan.newDaily),months=(days/30.44).toFixed(1),done=state.activity[todayKey()]||0,due=Object.values(state.reviews).filter(v=>v.due<=Date.now()).length;$('todayBody').innerHTML=`<div class="plan"><p><b>الحفظ الجديد:</b> ${done} من ${state.plan.newDaily} آيات اليوم.</p><p><b>المراجعة المستحقة:</b> ${due} آية.</p><p><b>المتبقي حتى الختم:</b> ${left} آية.</p><p><b>المدة التقديرية:</b> ${days} يومًا، نحو ${months} شهرًا، إذا حافظت على المعدل الحالي.</p></div>`}
function renderStats(){const m=Object.keys(state.mastered).length,p=Math.min(100,m/TOTAL*100),due=Object.values(state.reviews).filter(v=>v.due<=Date.now()).length,s=streakCount();$('overall').textContent=p.toFixed(1)+'%';$('overallBar').style.width=p+'%';$('mastered').textContent=m;$('reviews').textContent=due;$('streak').textContent=s;const acc=state.tests.total?Math.round(state.tests.correct/state.tests.total*100):0;$('statsBody').innerHTML=`<p>جلسات الحفظ: <b>${state.sessions}</b></p><p>الآيات المحفوظة: <b>${m}</b> من ${TOTAL}</p><p>الإنجاز: <b>${p.toFixed(2)}%</b></p><p>نتيجة اختبارات الاختيار: <b>${state.tests.correct}/${state.tests.total}</b> (${acc}%)</p><p>الاستمرار الحالي: <b>${s}</b> يوم</p>`}
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quran-hifz-backup.json';a.click();URL.revokeObjectURL(a.href)};$('importFile').onchange=e=>{const r=new FileReader();r.onload=()=>{try{JSON.parse(r.result);localStorage.setItem('hifzState',r.result);location.reload()}catch(_){alert('ملف النسخة الاحتياطية غير صالح.')}};r.readAsText(e.target.files[0])};$('resetBtn').onclick=()=>{if(confirm('سيتم حذف كل تقدم الحفظ والمراجعة. هل أنت متأكد؟')){localStorage.removeItem('hifzState');location.reload()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');init();

window.selfTest=(r,k)=>{state.tests.total++;if(r>0)state.tests.correct++;let v=state.reviews[k]||{level:1,due:Date.now()};v.level=Math.max(1,Math.min(7,v.level+(r===2?1:r===0?-1:0)));const days=r===0?0:r===1?2:Math.min(60,[1,2,4,7,14,30,60][v.level-1]);v.due=Date.now()+days*DAY;state.reviews[k]=v;save();$('startTest').click()};
function renderWeak(){const rows=Object.entries(state.reviews).filter(([k,v])=>state.mastered[k]).sort((a,b)=>a[1].level-b[1].level||a[1].due-b[1].due);if(!rows.length){$('weakBody').innerHTML='<p>لا توجد بيانات كافية بعد. ابدأ الحفظ والمراجعة ليحدد النظام نقاط الضعف.</p>';return}const weak=rows.filter(([,v])=>v.level<=2);$('weakBody').innerHTML=(weak.length?weak:rows.slice(0,10)).slice(0,30).map(([k,v])=>{const [sn,an]=k.split(':').map(Number),name=surahs.find(x=>x.number===sn)?.name||('السورة '+sn);return `<div class="card" style="margin:8px 0"><b>${name} • الآية ${an}</b> <span class="pill">مستوى الإتقان ${v.level}/7</span><div class="progress" style="margin-top:8px"><i style="width:${v.level/7*100}%"></i></div></div>`}).join('')};

// V4 — مركز التثبيت وسجل الأخطاء
state.mistakes=state.mistakes||{};
function savedKeys(){return Object.keys(state.mastered)}
async function ayahByKey(k){const [s,a]=k.split(':').map(Number),all=await getSurah(s);return {s,a,x:all[a-1],all}}
function recordMistake(k){state.mistakes[k]=(state.mistakes[k]||0)+1;let v=state.reviews[k]||{level:1,due:Date.now()};v.level=Math.max(1,v.level-1);v.due=Date.now();state.reviews[k]=v;save();renderMistakes()}
function renderMistakes(){const box=$('mistakeLog');if(!box)return;const rows=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,20);box.innerHTML=rows.length?rows.map(([k,n])=>{const [s,a]=k.split(':');const name=surahs.find(x=>x.number==s)?.name||('السورة '+s);return `<div class="card" style="margin:7px 0"><b>${name} • الآية ${a}</b> <span class="pill">${n} خطأ</span></div>`}).join(''):'<p class="muted">لا توجد أخطاء مسجلة حتى الآن.</p>'}
$('startAdvanced').onclick=async()=>{const keys=savedKeys();if(!keys.length)return alert('سجّل بعض الآيات كمحفوظة أولاً.');let type=$('advancedType').value,pool=keys;if(type==='weaktest'){pool=keys.filter(k=>(state.reviews[k]?.level||1)<=2||state.mistakes[k]);if(!pool.length)pool=keys}const k=pool[Math.floor(Math.random()*pool.length)],o=await ayahByKey(k),words=o.x.text.split(' '),cut=Math.max(1,Math.floor(words.length/2));if(type==='starts'){$('advancedArea').innerHTML=`<div class="testbox">أكمل الآية من بدايتها:<br><b>${words.slice(0,Math.min(4,cut)).join(' ')}</b> …</div>${advButtons(k,o.x.text)}`}
else if(type==='ends'){$('advancedArea').innerHTML=`<div class="testbox">اذكر بداية الآية التي تنتهي بـ:<br>… <b>${words.slice(-Math.min(4,words.length)).join(' ')}</b></div>${advButtons(k,o.x.text)}`}
else if(type==='links'){const next=o.all[o.a];if(!next)return $('startAdvanced').click();$('advancedArea').innerHTML=`<div class="testbox">سمّع الآية التالية بعد:<br><b>${o.x.text}</b></div>${advButtons(`${o.s}:${o.a+1}`,next.text)}`}
else {$('advancedArea').innerHTML=`<div class="testbox">موضع يحتاج إلى تثبيت:<br><b>${o.x.text}</b><br><small>سمّع ما بعده ثم قيّم نفسك</small></div>${advButtons(k,o.x.text)}`}}
function advButtons(k,answer){return `<button onclick="advReveal(this,'${k}',${JSON.stringify(answer).replace(/'/g,"&#39;")})">إظهار الإجابة</button><div class="row" style="margin-top:8px"><button onclick="advRate('${k}',0)">أخطأت</button><button onclick="advRate('${k}',1)">جيد</button><button class="primary" onclick="advRate('${k}',2)">متقن</button></div>`}
window.advReveal=(b,k,t)=>{const d=document.createElement('div');d.className='ayah';d.textContent=t;b.after(d)};
window.advRate=(k,r)=>{state.tests.total++;if(r>0)state.tests.correct++;if(r===0)recordMistake(k);else {let v=state.reviews[k]||{level:1,due:Date.now()};v.level=Math.min(7,v.level+(r===2?1:0));v.due=Date.now()+(r===2?7:2)*DAY;state.reviews[k]=v;save()}$('startAdvanced').click()};
const oldRenderStats=renderStats;renderStats=function(){oldRenderStats();const totalMistakes=Object.values(state.mistakes||{}).reduce((a,b)=>a+b,0);$('statsBody').innerHTML+=`<p>الأخطاء المسجلة للتثبيت: <b>${totalMistakes}</b></p>`};
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='advanced')renderMistakes()}));
renderMistakes();

// V5 — لوحة الإتقان والخطة الذكية والاختبارات الشاملة
state.history=state.history||[];
function levelOf(k){return Math.max(1,Math.min(7,state.reviews[k]?.level||1))}
function masteryPercent(keys){if(!keys.length)return 0;return Math.round(keys.reduce((n,k)=>n+levelOf(k),0)/(keys.length*7)*100)}
function classifyPlan(){const keys=savedKeys(),now=Date.now();const weak=keys.filter(k=>levelOf(k)<=2||state.mistakes[k]).sort((a,b)=>levelOf(a)-levelOf(b));const near=keys.filter(k=>{const v=state.reviews[k];return v&&v.due<=now+3*DAY&&levelOf(k)>2});const old=keys.filter(k=>levelOf(k)>=5).sort((a,b)=>(state.reviews[a]?.due||0)-(state.reviews[b]?.due||0));return {weak:weak.slice(0,8),near:near.slice(0,12),old:old.slice(0,10)}}
function keyLabel(k){const [s,a]=k.split(':').map(Number);return `${surahs.find(x=>x.number===s)?.name||'السورة '+s} • ${a}`}
async function buildMastery(){const keys=savedKeys(),box=$('masterySummary');if(!box)return;const pct=masteryPercent(keys),strong=keys.filter(k=>levelOf(k)>=5).length,weak=keys.filter(k=>levelOf(k)<=2||state.mistakes[k]).length;box.innerHTML=`<div class="card"><div class="muted">إتقان المحفوظ</div><div class="stat">${pct}%</div></div><div class="card"><div class="muted">مواضع قوية</div><div class="stat">${strong}</div></div><div class="card"><div class="muted">تحتاج تثبيت</div><div class="stat">${weak}</div></div>`;renderSmartPlan();renderSurahMastery();await renderJuzMastery()}
function renderSmartPlan(){const p=classifyPlan(),newLeft=Math.max(0,state.plan.newDaily-(state.activity[todayKey()]||0));$('smartPlan').innerHTML=`<div class="planGrid"><div class="planItem"><b>حفظ جديد</b><div class="score">${newLeft} آيات</div><span class="muted">المتبقي من هدف اليوم</span></div><div class="planItem"><b>مراجعة قريبة</b><div class="score">${p.near.length} موضعًا</div><span class="muted">مستحقة أو قريبة الاستحقاق</span></div><div class="planItem"><b>مراجعة قديمة</b><div class="score">${p.old.length} مواضع</div><span class="muted">لمنع ضعف المحفوظ المتقن</span></div><div class="planItem"><b>نقاط الضعف</b><div class="score">${p.weak.length} مواضع</div><span class="muted">للتثبيت اليوم</span></div></div>`}
function renderSurahMastery(){const groups={};savedKeys().forEach(k=>{const s=+k.split(':')[0];(groups[s]??=[]).push(k)});const rows=Object.entries(groups).sort((a,b)=>a[0]-b[0]);$('surahMastery').innerHTML=rows.length?rows.map(([s,ks])=>{const meta=surahs.find(x=>x.number==s),pct=masteryPercent(ks),coverage=meta?Math.round(ks.length/meta.numberOfAyahs*100):0;return `<div class="masteryRow"><b>${meta?.name||'السورة '+s}</b><div><div class="miniBar"><i style="width:${pct}%"></i></div><span class="muted">محفوظ ${coverage}% • إتقان ${pct}%</span></div><b>${ks.length}</b></div>`}).join(''):'<p class="muted">لا توجد آيات مسجلة كمحفوظة بعد.</p>'}
async function renderJuzMastery(){const groups={};for(const k of savedKeys()){try{const o=await ayahByKey(k),j=o.x.juz||0;if(j)(groups[j]??=[]).push(k)}catch(e){}}const rows=Object.entries(groups).sort((a,b)=>a[0]-b[0]);$('juzMastery').innerHTML=rows.length?rows.map(([j,ks])=>{const pct=masteryPercent(ks);return `<div class="masteryRow"><b>الجزء ${j}</b><div><div class="miniBar"><i style="width:${pct}%"></i></div><span class="muted">إتقان الآيات المحفوظة في الجزء ${pct}%</span></div><b>${ks.length}</b></div>`}).join(''):'<p class="muted">تظهر الأجزاء بعد تحميل السور التي حفظت منها.</p>'}
async function makeComprehensive(){const keys=savedKeys();if(!keys.length)return alert('سجّل بعض الآيات كمحفوظة أولاً.');const pool=shuffle(keys).slice(0,Math.min(5,keys.length)),items=[];for(const k of pool){const o=await ayahByKey(k);items.push(`<div class="card" style="margin:8px 0"><b>${keyLabel(k)}</b><div class="testbox">${o.x.text}</div><small>سمّع ما بعدها دون النظر، ثم قيّم الموضع.</small><div class="row"><button onclick="v5rate('${k}',0)">أخطأت</button><button onclick="v5rate('${k}',1)">جيد</button><button class="primary" onclick="v5rate('${k}',2)">متقن</button></div></div>`)}$('masteryTestArea').innerHTML=`<h3>اختبار شامل • ${items.length} مواضع</h3>`+items.join('')}
async function makePageTest(){const candidates=[];for(const k of savedKeys()){try{const o=await ayahByKey(k);if(o.x.page&&o.all[o.a-2]?.page!==o.x.page)candidates.push({k,o})}catch(e){}}if(!candidates.length)return alert('لا توجد بداية صفحة محفوظة ضمن السور المحمّلة حاليًا.');const {k,o}=candidates[Math.floor(Math.random()*candidates.length)];$('masteryTestArea').innerHTML=`<div class="testbox">اختبار ربط الصفحات<br><b>ابدأ من أول آية محفوظة في الصفحة ${o.x.page}</b><br>${o.x.text}</div><p class="muted">سمّع الصفحة أو ما تستطيع منها، ثم قيّم الربط من بداية الصفحة.</p><div class="row"><button onclick="v5rate('${k}',0)">تعثر</button><button onclick="v5rate('${k}',1)">جيد</button><button class="primary" onclick="v5rate('${k}',2)">متقن</button></div>`}
window.v5rate=(k,r)=>{state.history.push({k,r,at:Date.now()});if(state.history.length>500)state.history=state.history.slice(-500);if(r===0)recordMistake(k);else{let v=state.reviews[k]||{level:1,due:Date.now()};v.level=Math.min(7,v.level+(r===2?1:0));v.due=Date.now()+(r===2?14:3)*DAY;state.reviews[k]=v;state.tests.total++;state.tests.correct++;save()}buildMastery()};
$('comprehensiveTest').onclick=makeComprehensive;$('pageLinkTest').onclick=makePageTest;
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='mastery')buildMastery()}));
const v5oldToday=renderToday;renderToday=function(){v5oldToday();const p=classifyPlan();$('todayBody').innerHTML+=`<hr><b>تقسيم التثبيت المقترح:</b> قريب ${p.near.length} • قديم ${p.old.length} • ضعف ${p.weak.length}`};

// V6 — التسميع الصوتي الذكي
state.voiceHistory=state.voiceHistory||[];
let voiceKey=null,voiceTarget='',voiceRec=null,voiceText='';
function normalizeQuran(t){return (t||'').normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/[^\u0621-\u063A\u0641-\u064A\s]/g,' ').replace(/\s+/g,' ').trim()}
function wordSimilarity(a,b){a=normalizeQuran(a).split(' ').filter(Boolean);b=normalizeQuran(b).split(' ').filter(Boolean);if(!b.length)return {pct:0,matched:0,total:a.length,missing:a};const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);const matched=dp[a.length][b.length],pct=Math.round(matched/Math.max(1,a.length)*100);const spoken=new Set(b),missing=a.filter(w=>!spoken.has(w));return {pct,matched,total:a.length,missing}}
async function newVoiceTest(){const keys=savedKeys();if(!keys.length)return alert('سجّل بعض الآيات كمحفوظة أولاً.');let pool=keys;if($('voiceMode').value==='weak'){pool=keys.filter(k=>levelOf(k)<=2||state.mistakes[k]);if(!pool.length)pool=keys}voiceKey=pool[Math.floor(Math.random()*pool.length)];const o=await ayahByKey(voiceKey);voiceTarget=o.x.text;voiceText='';$('voicePrompt').innerHTML=`<div class="card"><b>${keyLabel(voiceKey)}</b><p>سمّع الآية كاملة دون النظر إلى النص.</p></div>`;$('voiceTranscript').textContent='سيظهر هنا النص الذي تعرف عليه المتصفح.';$('voiceResult').innerHTML='';$('voiceStatus').textContent='جاهز للتسميع.'}
function finishVoice(){if(!voiceKey||!voiceText.trim())return;const c=wordSimilarity(voiceTarget,voiceText),grade=c.pct>=90?2:c.pct>=70?1:0;state.voiceHistory.push({k:voiceKey,pct:c.pct,at:Date.now(),heard:voiceText});if(state.voiceHistory.length>200)state.voiceHistory=state.voiceHistory.slice(-200);state.tests.total++;if(grade>0)state.tests.correct++;if(grade===0)recordMistake(voiceKey);else{let v=state.reviews[voiceKey]||{level:1,due:Date.now()};if(grade===2)v.level=Math.min(7,v.level+1);v.due=Date.now()+(grade===2?7:2)*DAY;state.reviews[voiceKey]=v;save()}const miss=c.missing.slice(0,12).join('، ');$('voiceResult').innerHTML=`<div class="card"><div class="stat">${c.pct}%</div><b>دقة مطابقة الكلمات التقريبية</b><p>تمت مطابقة ${c.matched} من ${c.total} كلمة بحسب التعرف الصوتي.</p>${miss?`<p class="muted">كلمات لم تظهر في النص المتعرّف عليه: ${miss}</p>`:''}<button onclick="document.getElementById('voiceReveal').click()">مقارنة بالنص الأصلي</button></div>`;save();renderStats()}
$('newVoiceTest').onclick=newVoiceTest;
$('voiceStart').onclick=()=>{if(!voiceKey)return alert('اختر موضعًا أولاً.');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('التعرف الصوتي غير مدعوم في هذا المتصفح. جرّب Chrome أو Edge محدثًا.');try{voiceRec=new SR();voiceRec.lang='ar-SA';voiceRec.continuous=true;voiceRec.interimResults=true;voiceText='';voiceRec.onstart=()=>{$('voiceStatus').textContent='يستمع الآن... سمّع الآية.'};voiceRec.onresult=e=>{let final='',interim='';for(let i=0;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t+' '}voiceText=(final+interim).trim();$('voiceTranscript').textContent=voiceText||'يستمع...'};voiceRec.onerror=e=>{$('voiceStatus').textContent='تعذر التعرف الصوتي: '+e.error};voiceRec.onend=()=>{$('voiceStatus').textContent='انتهى الاستماع.';finishVoice()};voiceRec.start()}catch(e){alert('تعذر تشغيل الميكروفون. تحقق من إذن الميكروفون.') }};
$('voiceStop').onclick=()=>{if(voiceRec)try{voiceRec.stop()}catch(e){}};
$('voiceReveal').onclick=()=>{if(!voiceTarget)return alert('اختر موضعًا أولاً.');$('voiceResult').innerHTML+=`<div class="ayah">${voiceTarget}</div>`};
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='voice'&&!voiceKey&&savedKeys().length)newVoiceTest()}));
const v6oldStats=renderStats;renderStats=function(){v6oldStats();const vh=state.voiceHistory||[],avg=vh.length?Math.round(vh.reduce((n,x)=>n+x.pct,0)/vh.length):0;$('statsBody').innerHTML+=`<p>اختبارات التسميع الصوتي: <b>${vh.length}</b> • متوسط المطابقة: <b>${avg}%</b></p>`};

// V7 — المصحف التفاعلي والمتشابهات
state.similarHistory=state.similarHistory||[];
let mushafCurrentPage=1, similarGroups=[];
function masteryClass(k){if(!state.mastered[k])return 'm-new';const l=levelOf(k);return l<=2?'m-weak':l<=4?'m-mid':'m-strong'}
async function getPage(p){const key='page_'+p,d=localStorage.getItem(key);if(d)return JSON.parse(d);const r=await fetch(`${API}/page/${p}/quran-uthmani`);if(!r.ok)throw Error();const j=await r.json(),a=j.data.ayahs;localStorage.setItem(key,JSON.stringify(a));return a}
async function renderMushafPage(p){p=Math.max(1,Math.min(604,+p||1));mushafCurrentPage=p;$('mushafPage').value=p;$('mushafBody').innerHTML='<p class="muted">جاري تحميل الصفحة...</p>';$('ayahTools').innerHTML='';try{const a=await getPage(p);let last=0,html='';for(const x of a){const s=x.surah?.number||0;if(s!==last){last=s;html+=`<div class="surahHead">${x.surah?.name||''}</div>`}const k=`${s}:${x.numberInSurah}`;html+=`<span class="mushafAyah ${masteryClass(k)}" data-k="${k}" title="اضغط لأدوات الآية">${x.text} ﴿${x.numberInSurah}﴾ </span>`}$('mushafBody').innerHTML=html||'<p>لا توجد بيانات.</p>';document.querySelectorAll('.mushafAyah').forEach(el=>el.onclick=()=>openAyahTools(el.dataset.k,p))}catch(e){$('mushafBody').innerHTML='<p>تعذر تحميل الصفحة. تحتاج للإنترنت عند فتح الصفحة أول مرة.</p>'}}
async function openAyahTools(k,p){const [s,a]=k.split(':').map(Number);let x;try{x=(await getPage(p)).find(v=>(v.surah?.number||0)===s&&v.numberInSurah===a)}catch(e){};$('ayahTools').innerHTML=`<div class="card" style="margin-top:12px"><b>${keyLabel(k)}</b><div class="row" style="margin-top:8px"><button class="primary" onclick="mushafMark('${k}')">${state.mastered[k]?'محفوظ ✓':'تسجيل كمحفوظ'}</button><button onclick="mushafQuickTest('${k}',${p})">اختبرني من هنا</button><button onclick="mushafLinkTest('${k}',${p})">اختبار الربط بما بعدها</button></div>${x?`<p class="muted">الصفحة ${p} • مستوى الإتقان ${state.mastered[k]?levelOf(k)+'/7':'غير محفوظ'}</p>`:''}</div>`}
window.mushafMark=k=>{state.mastered[k]=true;state.reviews[k]=state.reviews[k]||{due:Date.now()+DAY,level:1};save();renderMushafPage(mushafCurrentPage)};
window.mushafQuickTest=async(k,p)=>{const a=await getPage(p),[s,n]=k.split(':').map(Number),i=a.findIndex(x=>(x.surah?.number||0)===s&&x.numberInSurah===n),x=a[i];if(!x)return;$('ayahTools').innerHTML=`<div class="testbox">${x.text}</div><p>أخفِ النص ذهنيًا ثم سمّع الآية التالية.</p><button class="primary" onclick="mushafReveal(${p},${i+1})">إظهار الإجابة</button>`};
window.mushafReveal=async(p,i)=>{const a=await getPage(p),x=a[i];$('ayahTools').innerHTML+=x?`<div class="ayah">${x.text} ﴿${x.numberInSurah}﴾</div>`:'<p>انتقلت الآية التالية إلى الصفحة التالية. استخدم اختبار الربط.</p>'};
window.mushafLinkTest=async(k,p)=>{let a=await getPage(p),[s,n]=k.split(':').map(Number),i=a.findIndex(x=>(x.surah?.number||0)===s&&x.numberInSurah===n),next=a[i+1];if(!next&&p<604){const b=await getPage(p+1);next=b[0]}const x=a[i];$('ayahTools').innerHTML=`<div class="testbox">${x?.text||''}</div><p>ما الآية التي تليها؟</p><button class="primary" id="revealLinkV7">إظهار</button>`;$('revealLinkV7').onclick=()=>{$('ayahTools').innerHTML+=next?`<div class="ayah">${next.text} ﴿${next.numberInSurah}﴾</div>`:'<p>هذه نهاية المصحف.</p>'}};
$('loadMushafPage').onclick=()=>renderMushafPage($('mushafPage').value);$('prevMushafPage').onclick=()=>renderMushafPage(mushafCurrentPage-1);$('nextMushafPage').onclick=()=>renderMushafPage(mushafCurrentPage+1);
function cachedAyahs(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!k.startsWith('surah_'))continue;try{const s=+k.slice(6),a=JSON.parse(localStorage.getItem(k));a.forEach(x=>out.push({k:`${s}:${x.numberInSurah}`,text:x.text,s,a:x.numberInSurah}))}catch(e){}}return out}
function similarSignature(t){return normalizeQuran(t).split(' ').filter(Boolean).slice(0,3).join(' ')}
function discoverSimilar(){const m={};for(const x of cachedAyahs()){const sig=similarSignature(x.text);if(sig.split(' ').length<3)continue;(m[sig]??=[]).push(x)}similarGroups=Object.entries(m).filter(([,v])=>v.length>1).map(([sig,v])=>({sig,items:v})).sort((a,b)=>b.items.length-a.items.length);$('similarSummary').innerHTML=similarGroups.length?`<p>تم اكتشاف <b>${similarGroups.length}</b> مجموعة ذات بدايات متشابهة ضمن السور المحملة على هذا الجهاز.</p>`:'<p class="muted">لم تظهر مجموعات كافية بعد. افتح أو حمّل سورًا أكثر ليتمكن النظام من المقارنة.</p>';return similarGroups}
function startSimilarTest(){if(!similarGroups.length)discoverSimilar();if(!similarGroups.length)return;const g=similarGroups[Math.floor(Math.random()*similarGroups.length)],x=g.items[Math.floor(Math.random()*g.items.length)],opts=shuffle(g.items).slice(0,4);$('similarArea').innerHTML=`<div class="testbox">${g.sig} ...</div><p>أي موضع من هذه المواضع تريد أن تكمل منه؟ اختر الموضع ثم سمّع بقيته قبل إظهار النص.</p>`+opts.map(o=>`<button class="choice" onclick="similarAnswer('${o.k}','${x.k}')">${keyLabel(o.k)}</button>`).join('')+`<button onclick="similarReveal('${x.k}')">إظهار الآية المختارة</button>`}
window.similarAnswer=(picked,target)=>{const ok=picked===target;state.similarHistory.push({picked,target,ok,at:Date.now()});state.tests.total++;if(ok)state.tests.correct++;else recordMistake(target);save();$('similarArea').innerHTML+=`<p><b>${ok?'صحيح':'يحتاج تثبيت'}</b> • الموضع المستهدف: ${keyLabel(target)}</p>`};
window.similarReveal=async k=>{try{const o=await ayahByKey(k);$('similarArea').innerHTML+=`<div class="ayah">${o.x.text}</div>`}catch(e){}};
$('buildSimilar').onclick=discoverSimilar;$('startSimilar').onclick=startSimilarTest;
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='mushaf'&&!$('mushafBody').innerHTML)renderMushafPage(mushafCurrentPage);if(b.dataset.tab==='similar')discoverSimilar()}));
const v7oldStats=renderStats;renderStats=function(){v7oldStats();const h=state.similarHistory||[],ok=h.filter(x=>x.ok).length;$('statsBody').innerHTML+=`<p>اختبارات المتشابهات: <b>${h.length}</b>${h.length?` • الدقة <b>${Math.round(ok/h.length*100)}%</b>`:''}</p>`};

// V8 — الجلسة اليومية التكيفية وخوارزمية الأولويات
state.dailyCoach=state.dailyCoach||{date:'',queue:[],index:0,completed:0};
function v8Level(k){return state.reviews[k]?.level||1}
function v8Mistakes(k){return (state.mistakes||[]).filter(x=>x.key===k||x.k===k).length}
function v8Priority(k){const r=state.reviews[k]||{due:0,level:1}, overdue=Math.max(0,(Date.now()-r.due)/DAY);return (8-r.level)*12+Math.min(30,overdue*3)+v8Mistakes(k)*6}
function v8Repeat(k){const l=v8Level(k),m=v8Mistakes(k);return Math.min(10,Math.max(2,8-l+Math.min(3,m)))}
function buildDailyCoach(){
 const keys=Object.keys(state.mastered), due=keys.filter(k=>(state.reviews[k]?.due||0)<=Date.now()).sort((a,b)=>v8Priority(b)-v8Priority(a));
 const weak=keys.filter(k=>v8Level(k)<=2).sort((a,b)=>v8Priority(b)-v8Priority(a));
 const old=keys.filter(k=>v8Level(k)>=5&&!due.includes(k)).sort((a,b)=>(state.reviews[a]?.due||0)-(state.reviews[b]?.due||0));
 const cap=Math.max(5,state.plan.reviewDaily||20), seen=new Set(), q=[];
 function add(arr,type,n){for(const k of arr){if(q.length>=cap||n<=0)break;if(!seen.has(k)){seen.add(k);q.push({type,key:k,repeats:v8Repeat(k)});n--}}}
 add(weak,'تثبيت نقطة ضعف',Math.ceil(cap*.35));add(due,'مراجعة مستحقة',Math.ceil(cap*.45));add(old,'مراجعة قديمة',Math.ceil(cap*.2));
 const newLeft=Math.max(0,(state.plan.newDaily||5)-(state.activity[todayKey()]||0));if(newLeft)q.unshift({type:'حفظ جديد',key:null,repeats:5,count:newLeft});
 state.dailyCoach={date:todayKey(),queue:q,index:0,completed:0};save();return q
}
async function renderDailyTask(){
 const c=state.dailyCoach;if(c.date!==todayKey()||!c.queue.length)buildDailyCoach();const t=state.dailyCoach.queue[state.dailyCoach.index],area=$('dailySessionArea');
 if(!t){area.innerHTML='<div class="dailyTask"><b>أحسنت، أنهيت جلسة اليوم.</b><p class="muted">يمكنك مواصلة المراجعة من قسم المراجعة أو بدء اختبار شامل.</p></div>';return}
 if(!t.key){area.innerHTML=`<div class="dailyTask"><span class="priority">${t.type}</span><h3>${t.count} آيات جديدة</h3><p>انتقل إلى جلسة الحفظ واختر الموضع التالي في خطتك. كرر كل آية مبدئيًا <span class="repeatBadge">${t.repeats} مرات</span> ثم اربطها بما قبلها.</p><button onclick="document.querySelector('[data-tab=memorize]').click()">فتح الحفظ</button><button class="primary" onclick="v8Done('good')">تمت المهمة</button></div>`;return}
 const [s,a]=t.key.split(':').map(Number),name=surahs.find(x=>x.number===s)?.name||('السورة '+s);let text='';try{const d=await loadSurah(s);text=d.find(x=>x.numberInSurah===a)?.text||''}catch(e){}
 area.innerHTML=`<div class="dailyTask"><span class="priority">${t.type}</span><h3>${name} • الآية ${a}</h3><div class="testbox hide" id="v8Ayah">${text||'حمّل السورة أولًا من قسم الحفظ.'}</div><p>التكرار المقترح: <span class="repeatBadge">${t.repeats} مرات</span> • مستوى الإتقان ${v8Level(t.key)}/7</p><div class="row"><button onclick="document.getElementById('v8Ayah').classList.toggle('hide')">إظهار/إخفاء</button><button onclick="v8Done('weak')">ضعيف</button><button onclick="v8Done('good')">جيد</button><button class="primary" onclick="v8Done('strong')">متقن</button></div></div>`
}
window.v8Done=function(rate){const c=state.dailyCoach,t=c.queue[c.index];if(t?.key){const r=state.reviews[t.key]||{level:1,due:Date.now()};if(rate==='weak'){r.level=Math.max(1,r.level-1);r.due=Date.now()+DAY}else if(rate==='good'){r.level=Math.min(7,r.level+1);r.due=Date.now()+DAY*Math.max(2,r.level*2)}else{r.level=Math.min(7,r.level+2);r.due=Date.now()+DAY*Math.max(7,r.level*5)}state.reviews[t.key]=r}c.index++;c.completed++;save();renderDailyTask();renderStats();renderReview();renderToday()}
$('startDailySession').onclick=()=>{buildDailyCoach();renderDailyTask()};$('nextDailyTask').onclick=()=>{if(state.dailyCoach.index<state.dailyCoach.queue.length)state.dailyCoach.index++;save();renderDailyTask()};
const v8Today=renderToday;renderToday=function(){v8Today();const c=state.dailyCoach,q=c.date===todayKey()?c.queue:[];$('todayBody').innerHTML+=`<div class="plan"><p><b>الجلسة الذكية:</b> ${c.date===todayKey()?c.completed:0} من ${q.length} مهام مكتملة.</p><p><b>قاعدة V8:</b> الأولوية للأخطاء المتكررة ثم المراجعات المستحقة ثم المحفوظ القديم.</p></div>`};
const v8Init=init;init=async function(){await v8Init();if(state.dailyCoach?.date===todayKey())renderDailyTask()};
